// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase project credentials
  // You can get these values from the Firebase Console:
  // 1. Go to https://console.firebase.google.com/
  // 2. Select your project
  // 3. Go to Project Settings (gear icon)
  // 4. Scroll down to "Your apps" and select the appropriate platform
  // 5. Copy the configuration values
  // 
  // Alternatively, run: flutterfire configure
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-U7bLeW3bQUasoRo0bkZzixNJgDc9kxs',
    appId: '1:140881193724:web:YOUR_WEB_APP_ID', // TODO: Add web app in Firebase Console if needed
    messagingSenderId: '140881193724',
    projectId: 'edaraapp-cb18b',
    authDomain: 'edaraapp-cb18b.firebaseapp.com',
    storageBucket: 'edaraapp-cb18b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-U7bLeW3bQUasoRo0bkZzixNJgDc9kxs',
    appId: '1:140881193724:android:ff1b4f459744bd25ad0579',
    messagingSenderId: '140881193724',
    projectId: 'edaraapp-cb18b',
    storageBucket: 'edaraapp-cb18b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-U7bLeW3bQUasoRo0bkZzixNJgDc9kxs',
    appId: '1:140881193724:ios:YOUR_IOS_APP_ID', // TODO: Add iOS app in Firebase Console if needed
    messagingSenderId: '140881193724',
    projectId: 'edaraapp-cb18b',
    storageBucket: 'edaraapp-cb18b.firebasestorage.app',
    iosBundleId: 'com.example.edaraHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-U7bLeW3bQUasoRo0bkZzixNJgDc9kxs',
    appId: '1:140881193724:ios:YOUR_MACOS_APP_ID', // TODO: Add macOS app in Firebase Console if needed
    messagingSenderId: '140881193724',
    projectId: 'edaraapp-cb18b',
    storageBucket: 'edaraapp-cb18b.firebasestorage.app',
    iosBundleId: 'com.example.edaraHubApp',
  );
}
